#!/bin/bash

JSON_FILE="data.json"

# Check if the JSON file exists
if [[ ! -f "$JSON_FILE" ]]; then
    echo "Error: JSON file '$JSON_FILE' not found. Please ensure the file existsand rerun the script."
     exit 1
fi

# Extract data using jq
RAW_OUTPUT=$(jq -r '{name: .name, height: .height, weight: .weight, type: .type[0].type.name} | @tsv' "$JSON_FILE")


# Parse the raw outpout using awk
echo "$RAW_OUTPUT" | awk -F'\t' '
{
    name=$1
    height=$2 / 10
    weight=$3 / 10
    type=$4
    printf "%s is of type %s, weighs %.1fkg, and is %.1fm tall.\n", name, type, weight, height}' | sed 's/\.0kg/kg/; s/\.0m/m/'
